### PR TITLE
Migrate template from existing repository to this repository

### PR DESCRIPTION
**Pull request by srjames-ukho**
- Copied the template from old repository into here
- Updated template with new paths
- Updated documentation

### CODE REVIEW

**Comment by elduddz** [comment]
@srjames-ukho could you remove yourself directly from the code owner?

**Comment by srjames-ukho** [comment]
> @srjames-ukho could you remove yourself directly from the code owner?

Ha, yeah.

**Comment by elduddz** [comment]
Cool, probably be the same for the admin role. I think you're in there and get access via the team as well.

**Comment by srjames-ukho** [comment]
> Cool, probably be the same for the admin role. I think you're in there and get access via the team as well.

I think I found what you meant, I removed myself.

**Comment by elduddz** [comment]
Can anyone from @UKHO/calypso comment on this as LGTM?

**Review by elerivaliant — APPROVED** [review]

**Comment by srjames-ukho** [comment]
Can someone from @UKHO/digital-delivery-capability give their blessing?

**Review by bolt-io — APPROVED** [review]

**Comment by elduddz** [comment]
:blessing: @srjames-ukho

**Comment by srjames-ukho** [comment]
> :blessing: @srjames-ukho

Thanks Saint Luke

**Pull request merged**
